webtalk_init -webtalk_dir C:/Users/datda/Downloads/jit_intern/i2c_controller/i2c_controller.sim/sim_1/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 29 11:31:27 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d8be9ddc-4904-4d8e-ac2d-f9766af5ab42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bd3ea96680974ebf88e6e6598e2bb076" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9348_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4234935483 -regid "" -xml C:/Users/datda/Downloads/jit_intern/i2c_controller/i2c_controller.sim/sim_1/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/datda/Downloads/jit_intern/i2c_controller/i2c_controller.sim/sim_1/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/datda/Downloads/jit_intern/i2c_controller/i2c_controller.sim/sim_1/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
